{
    "script" : "example/date.sh",
    "language" : "shell",
    "send_script" : true,
    "priority" : 8,
    "job_timeout" : 120,
    "queue_timeout" : 60,
    "task_timeout" : 15,
    "max_failed_nodes" : -1,
    "num_execution" : -1,
    "max_cluster_instances" : -1,
    "max_worker_instances" : 1,
    "exclusive" : true,
    "no_reschedule" : true,
    "max_exec_at_worker" : 1,
    "exec_unit_type" : "host",
    "cron" : "* * * * *",
    "name" : "my_cron_job"
}
