#ifndef __ERROR_CODE_H
#define __ERROR_CODE_H

#define NODE_FATAL -1
#define NODE_JOB_COMPLETION_NOT_FOUND -2
#define NODE_JOB_TIMEOUT -3
#define NODE_LANG_NOT_SUPPORTED -4
#define NODE_SCRIPT_EXEC_FAILED -5
#define NODE_TASK_NOT_FOUND -6
#define NODE_SCRIPT_FILE_NOT_FOUND -7

#endif
